### PR TITLE
Rewrite P/Invoke generator using Roslyn

### PR DESCRIPTION
**Pull request by FiniteReality**
**NOTE:** This is super *super* alpha; all I did was get a small sample application working before pushing these commits for now.

Rewriting the P/Invoke generator using Roslyn should allow us in the future to modify it to work with new features like source generators, which could make generating P/Invoke signatures *really* easy. (See #127)

However, no current public API has been properly designed or considered; what is here is currently the "bare minimum" in order to get something working. I do hope that this minimal example can solicit some dialogue, and hopefully eventually a final design.

### CODE REVIEW

**Comment by tannergooding** [comment]
Thanks @FiniteReality. I might take this and see if I can get a more complete sample working, is that alright with you?

**Comment by FiniteReality** [comment]
Fine with me - the current "sample" I'm working with is some code I borrowed from the Doxygen documentation:
```
typedef unsigned long long some_type;
/*! \brief a normal member taking two arguments and returning an integer value.
 *  \param a an integer argument.
 *  \param s a constant character pointer.
 *  \sa Javadoc_Test()
 *  \sa ~Javadoc_Test()
 *  \sa testMeToo()
 *  \sa publicVar()
 *  \return The test results
 */
some_type testMe(some_type a,const char *s);
```

I'm then simply iterating through the function declarations and using PInvokeMethodBuilder on them.

**Comment by PathogenDavid** [comment]
> Roslyn should allow us in the future to modify it to work with new features like source generators

While I don't doubt that this is a good idea in general, does this change actually accomplish this goal?

I am under the impression that source generators emit instances of `SourceText`, which are essentially unparsed strings rather than the syntax nodes emitted from `SyntaxFactory` as with this PR.

**Comment by FiniteReality** [comment]
> While I don't doubt that this is a good idea in general, does this change actually accomplish this goal?

Not by itself, of course :stuck_out_tongue: 

> I am under the impression that source generators emit instances of SourceText, which are essentially unparsed strings rather than the syntax nodes emitted from SyntaxFactory as with this PR.

Yeah, but by returning a full syntax tree, we make it easier to integrate with extensions. For example, if you had an extension to ClangSharp which allowed it to properly read Qt signals and slots and translate those to events, exposing the full syntax tree makes it easier to integrate those with the P/Invoke generator, in my opinion.

**Comment by PathogenDavid** [comment]
Roger that, thanks for the clarification!

**Pull request closed without merging**
